apiVersion: 1

datasources:
  - name: Prometheus-Local
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: VictoriaMetrics-LongTerm
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428